name: Atualizar Dados Solana

on:
  schedule:
    - cron: "0 */6 * * *"  # Executa a cada 6 horas
  workflow_dispatch:  # Permite executar manualmente

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Instalar dependências
      run: pip install numpy requests

    - name: Executar script de atualização
      run: |
        python - <<EOF
        import requests, json, numpy as np

        URL = "https://api.coingecko.com/api/v3/coins/solana/market_chart?vs_currency=usd&days=30"
        data = requests.get(URL).json()
        precos = [p[1] for p in data['prices']]
        preco_atual = precos[-1]
        retornos = np.diff(precos) / precos[:-1]
        volatilidade = np.std(retornos)
        coef = np.polyfit(np.arange(len(precos)), precos, 1)
        tendencia = coef[0]
        previsoes_sarima = [preco_atual + i * coef[0] for i in range(1, 5)]
        previsoes_holtwinters = [preco_atual + i * coef[0] * 1.1 for i in range(1, 5)]

        with open("data.json", "w") as f:
            json.dump({
                "precoAtual": preco_atual,
                "volatilidade": float(volatilidade),
                "tendencia": float(tendencia),
                "previsoesSARIMA": previsoes_sarima,
                "previsoesHoltWinters": previsoes_holtwinters
            }, f, indent=4)
        EOF

    - name: Commit e push dos dados atualizados
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data.json
        git commit -m "Atualização automática dos dados"
        git push